---
title: "ST4248 Project"
author: "Group C4"
date: '2023-03-02'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries Import

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(reshape2)
```

# Dataset Import

```{r}
resale = read.csv("data/resale-flat-prices-based-on-registration-date-from-jan-2017-onwards.csv")
resale_2023 = resale %>% 
  filter(month %in% c("2023-01", "2023-02"))
resale_2023
```

# Data Preparation

```{r}
# HDB lease is 99 years so remaining_lease is 99 - (2023 - lease_commence_date), 
# so we can safely remove lease_commence_date
resale_2023 = resale_2023 %>%
  separate(remaining_lease, c("remaining_years", "years", "remaining_months", "months")) %>%
  mutate(remaining_lease = as.integer(remaining_years) + 
           ifelse(is.na(remaining_months), 0, as.integer(remaining_months) / 12)) %>%
  select(-c(lease_commence_date, remaining_years, remaining_months, years, months))
```

```{r}
sum(is.na(resale_2023))
```

# EDA

```{r}
summary(resale_2023)
str(resale_2023)
```

```{r}
# can help to change into ggplot and add more charts (esp correlation and relationship with price)
barplot(table(resale_2023$month))
barplot(table(resale_2023$town))
barplot(table(resale_2023$flat_type))
length(unique(resale_2023$block))
barplot(table(resale_2023$street_name))
barplot(table(resale_2023$storey_range))
barplot(table(resale_2023$floor_area_sqm))
barplot(table(resale_2023$flat_model))
barplot(table(resale_2023$remaining_lease))
barplot(table(resale_2023$resale_price))
```

```{r}
resale_2023 %>% 
  ggplot() +
  geom_boxplot(aes(x = month, y = resale_price))

resale_2023 %>% 
  ggplot() +
  geom_boxplot(aes(x = town, y = resale_price))

resale_2023 %>% 
  ggplot() +
  geom_boxplot(aes(x = flat_type, y = resale_price))

resale_2023 %>% 
  ggplot() +
  geom_boxplot(aes(x = flat_type, y = resale_price)) +
  facet_wrap(~flat_model, scales = "free_x")

resale_2023 %>% 
  ggplot() +
  geom_boxplot(aes(x = flat_model, y = resale_price)) +
  facet_wrap(~flat_type, scales = "free_x")

resale_2023 %>% 
  ggplot() +
  geom_boxplot(aes(x = storey_range, y = resale_price))

resale_2023 %>% 
  ggplot() +
  geom_point(aes(x = floor_area_sqm, y = resale_price))

resale_2023 %>% 
  ggplot() +
  geom_boxplot(aes(x = flat_model, y = resale_price))

resale_2023 %>% 
  ggplot() +
  geom_point(aes(x = remaining_lease, y = resale_price))

resale_2023 %>%
  ggplot() +
  geom_histogram(aes(x = resale_price)) +
  labs(title = "Resale Price Distribution") +
  ylab("Count") +
  xlab("Resale Price") +
  theme_minimal()

resale_2023 %>%
  ggplot(aes(sample = resale_price)) +
  stat_qq() +
  stat_qq_line() +
  labs(title = "Resale Price QQ Plot") +
  ylab("Sample Quantiles") +
  xlab("Theoretical Quantiles") +
  theme_minimal()

resale_2023 %>%
  ggplot() +
  geom_histogram(aes(x = remaining_lease))

resale_2023 %>%
  ggplot() +
  geom_histogram(aes(x = floor_area_sqm))
```

```{r}
cormat <- round(cor(resale_2023[, c("floor_area_sqm", "remaining_lease", "resale_price")]),2)
head(cormat)

melted_cormat <- melt(cormat)
head(melted_cormat)

ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile() +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                       midpoint = 0, limit = c(-1,1), space = "Lab", 
                       name="Pearson\nCorrelation") +
  geom_text(aes(Var2, Var1, label = value), color = "black", size = 4)
```

```{r}
# just playing around
resale_2023.lm = lm(resale_price ~ ., data = resale_2023)
summary(resale_2023.lm)
y_pred = predict(resale_2023.lm, resale_2023)
plot(y_pred, resale_2023[, "resale_price"])
```