---
title: "ST4248 Project"
author: "Group C4"
date: '2023-03-02'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries Import

```{r}
library(dplyr)
library(tidyr)
library(randomForest)
```

# Import CSV

```{r}
# I did this before I did feature selection so need to change abit
resale = read.csv("data/feature_engineering/resale_feature_engineering.csv")
total_rows = dim(resale)[1]
train_indices = sample(total_rows, 0.8 * total_rows)

resale_train = resale[train_indices,]
resale_test = resale[-train_indices,]

dim(resale_train)
dim(resale_test)

resale_train_ori = resale_train[, 1:10]
resale_test_ori = resale_test[, 1:10]
```

# Bagging

```{r}
set.seed(1)

#to be finetuned?
bag.resale = randomForest(resale_price ~ ., data = resale_train_ori, mtry = 9, importance = TRUE)
yhat.bag = predict(bag.resale, newdata = resale_test_ori)

sqrt(mean((yhat.bag - resale_test_ori[,"resale_price"])^2))
rss = sum((yhat.bag - resale_test_ori[,"resale_price"]) ^ 2)  ## residual sum of squares
tss = sum((resale_test_ori[,"resale_price"] - mean(resale_test_ori[,"resale_price"])) ^ 2)  ## total sum of squares
rsq = 1 - rss/tss
rsq

a.rsq = 1 - (1 - rsq) * (dim(resale_test)[1] - 1) / (dim(resale_test)[1] - dim(resale_train)[2])
a.rsq

summary(yhat.bag)
importance(bag.resale)
varImpPlot(bag.resale)
```

```{r}
set.seed(1)

#to be finetuned?
bag.resale = randomForest(resale_price ~ ., data = resale_train, mtry = 9, importance = TRUE)
yhat.bag = predict(bag.resale, newdata = resale_test)

sqrt(mean((yhat.bag - resale_test[,"resale_price"])^2))
rss = sum((yhat.bag - resale_test[,"resale_price"]) ^ 2)  ## residual sum of squares
tss = sum((resale_test[,"resale_price"] - mean(resale_test[,"resale_price"])) ^ 2)  ## total sum of squares
rsq = 1 - rss/tss
rsq

a.rsq = 1 - (1 - rsq) * (dim(resale_test)[1] - 1) / (dim(resale_test)[1] - dim(resale_train)[2])
a.rsq

summary(yhat.bag)
importance(bag.resale)
varImpPlot(bag.resale)
```